# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_account_short_title', models.CharField(max_length=50, verbose_name='short title')),
                ('cd_account_title', models.CharField(max_length=125, verbose_name='title')),
            ],
        ),
    ]
